#include "./device_carrier_cfg.h"
#include "../../../isr/isr_config.h"
#include "../../../inc/driver/driver_dma/driver_dma.h"

device_carrier_cfg_t device_carrier_cfg_table[DEVICE_CARRIER_COUNT] =
{
    {
        .carrier_id = DEVICE_CARRIER_1,
        .dma_cfg =
        {
            .dma_module = &MODULE_DMA,
            .dma_modulecfg.dma = &MODULE_DMA,
            .dma_channelcfg.module = NULL_PTR,
            .dma_channelcfg.channelId = DMA_CHANNEL_CARRIER1,
            .dma_channelcfg.sourceAddress = 0,
            .dma_channelcfg.destinationAddress = 0,
            .dma_channelcfg.shadowAddress = 0,
            .dma_channelcfg.readDataCrc = 0,
            .dma_channelcfg.sourceDestinationAddressCrc = 0,
            .dma_channelcfg.transferCount = 6,
            .dma_channelcfg.blockMode = IfxDma_ChannelMove_1,
            .dma_channelcfg.requestMode = IfxDma_ChannelRequestMode_oneTransferPerRequest,
            .dma_channelcfg.operationMode = IfxDma_ChannelOperationMode_continuous,
            .dma_channelcfg.moveSize = IfxDma_ChannelMoveSize_16bit,
            .dma_channelcfg.pattern = IfxDma_ChannelPattern_0_disable,
            .dma_channelcfg.requestSource = IfxDma_ChannelRequestSource_peripheral,
            .dma_channelcfg.busPriority = DMA_PRIORITY_CARRIER1,
            .dma_channelcfg.hardwareRequestEnabled = TRUE,
            .dma_channelcfg.sourceAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.sourceAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.sourceAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.destinationAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.destinationAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.destinationAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.shadowControl = IfxDma_ChannelShadow_none,
            .dma_channelcfg.sourceCircularBufferEnabled = FALSE,
            .dma_channelcfg.destinationCircularBufferEnabled = FALSE,
            .dma_channelcfg.timestampEnabled = FALSE,
            .dma_channelcfg.wrapSourceInterruptEnabled = FALSE,
            .dma_channelcfg.wrapDestinationInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptEnabled = TRUE,
            .dma_channelcfg.channelInterruptControl = IfxDma_ChannelInterruptControl_thresholdLimitMatch,
            .dma_channelcfg.interruptRaiseThreshold = 0,
            .dma_channelcfg.transactionRequestLostInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptPriority = ISR_CONFIG_PRIORITY_CARRIER1_BUSINESS_INTERRUPT,
            .dma_channelcfg.channelInterruptTypeOfService = ISR_CONFIG_TOS_CARRIER1_BUSINESS_INTERRUPT,
        },
    },
    {
        .carrier_id = DEVICE_CARRIER_2,
        .dma_cfg =
        {
            .dma_module = &MODULE_DMA,
            .dma_modulecfg.dma = &MODULE_DMA,
            .dma_channelcfg.module = NULL_PTR,
            .dma_channelcfg.channelId = DMA_CHANNEL_CARRIER2,
            .dma_channelcfg.sourceAddress = 0,
            .dma_channelcfg.destinationAddress = 0,
            .dma_channelcfg.shadowAddress = 0,
            .dma_channelcfg.readDataCrc = 0,
            .dma_channelcfg.sourceDestinationAddressCrc = 0,
            .dma_channelcfg.transferCount = 0,
            .dma_channelcfg.blockMode = IfxDma_ChannelMove_1,
            .dma_channelcfg.requestMode = IfxDma_ChannelRequestMode_oneTransferPerRequest,
            .dma_channelcfg.operationMode = IfxDma_ChannelOperationMode_continuous,
            .dma_channelcfg.moveSize = IfxDma_ChannelMoveSize_8bit,
            .dma_channelcfg.pattern = IfxDma_ChannelPattern_0_disable,
            .dma_channelcfg.requestSource = IfxDma_ChannelRequestSource_peripheral,
            .dma_channelcfg.busPriority = DMA_PRIORITY_CARRIER2,
            .dma_channelcfg.hardwareRequestEnabled = TRUE,
            .dma_channelcfg.sourceAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.sourceAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.sourceAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.destinationAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.destinationAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.destinationAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.shadowControl = IfxDma_ChannelShadow_none,
            .dma_channelcfg.sourceCircularBufferEnabled = TRUE,
            .dma_channelcfg.destinationCircularBufferEnabled = TRUE,
            .dma_channelcfg.timestampEnabled = FALSE,
            .dma_channelcfg.wrapSourceInterruptEnabled = FALSE,
            .dma_channelcfg.wrapDestinationInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptEnabled = TRUE,
            .dma_channelcfg.channelInterruptControl = IfxDma_ChannelInterruptControl_thresholdLimitMatch,
            .dma_channelcfg.interruptRaiseThreshold = 0,
            .dma_channelcfg.transactionRequestLostInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptPriority = ISR_CONFIG_PRIORITY_CARRIER2_BUSINESS_INTERRUPT,
            .dma_channelcfg.channelInterruptTypeOfService = ISR_CONFIG_TOS_CARRIER2_BUSINESS_INTERRUPT,
        },
    },
    {
        .carrier_id = DEVICE_CARRIER_3,
        .dma_cfg =
        {
            .dma_module = &MODULE_DMA,
            .dma_modulecfg.dma = &MODULE_DMA,
            .dma_channelcfg.module = NULL_PTR,
            .dma_channelcfg.channelId = DMA_CHANNEL_CARRIER3,
            .dma_channelcfg.sourceAddress = 0,
            .dma_channelcfg.destinationAddress = 0,
            .dma_channelcfg.shadowAddress = 0,
            .dma_channelcfg.readDataCrc = 0,
            .dma_channelcfg.sourceDestinationAddressCrc = 0,
            .dma_channelcfg.transferCount = 0,
            .dma_channelcfg.blockMode = IfxDma_ChannelMove_1,
            .dma_channelcfg.requestMode = IfxDma_ChannelRequestMode_oneTransferPerRequest,
            .dma_channelcfg.operationMode = IfxDma_ChannelOperationMode_continuous,
            .dma_channelcfg.moveSize = IfxDma_ChannelMoveSize_8bit,
            .dma_channelcfg.pattern = IfxDma_ChannelPattern_0_disable,
            .dma_channelcfg.requestSource = IfxDma_ChannelRequestSource_peripheral,
            .dma_channelcfg.busPriority = DMA_PRIORITY_CARRIER3,
            .dma_channelcfg.hardwareRequestEnabled = TRUE,
            .dma_channelcfg.sourceAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.sourceAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.sourceAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.destinationAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.destinationAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.destinationAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.shadowControl = IfxDma_ChannelShadow_none,
            .dma_channelcfg.sourceCircularBufferEnabled = TRUE,
            .dma_channelcfg.destinationCircularBufferEnabled = TRUE,
            .dma_channelcfg.timestampEnabled = FALSE,
            .dma_channelcfg.wrapSourceInterruptEnabled = FALSE,
            .dma_channelcfg.wrapDestinationInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptEnabled = TRUE,
            .dma_channelcfg.channelInterruptControl = IfxDma_ChannelInterruptControl_thresholdLimitMatch,
            .dma_channelcfg.interruptRaiseThreshold = 0,
            .dma_channelcfg.transactionRequestLostInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptPriority = ISR_CONFIG_PRIORITY_CARRIER3_BUSINESS_INTERRUPT,
            .dma_channelcfg.channelInterruptTypeOfService = ISR_CONFIG_TOS_CARRIER3_BUSINESS_INTERRUPT,
        },
    },
    {
        .carrier_id = DEVICE_CARRIER_4,
        .dma_cfg =
        {
            .dma_module = &MODULE_DMA,
            .dma_modulecfg.dma = &MODULE_DMA,
            .dma_channelcfg.module = NULL_PTR,
            .dma_channelcfg.channelId = DMA_CHANNEL_CARRIER4,
            .dma_channelcfg.sourceAddress = 0,
            .dma_channelcfg.destinationAddress = 0,
            .dma_channelcfg.shadowAddress = 0,
            .dma_channelcfg.readDataCrc = 0,
            .dma_channelcfg.sourceDestinationAddressCrc = 0,
            .dma_channelcfg.transferCount = 0,
            .dma_channelcfg.blockMode = IfxDma_ChannelMove_1,
            .dma_channelcfg.requestMode = IfxDma_ChannelRequestMode_oneTransferPerRequest,
            .dma_channelcfg.operationMode = IfxDma_ChannelOperationMode_continuous,
            .dma_channelcfg.moveSize = IfxDma_ChannelMoveSize_8bit,
            .dma_channelcfg.pattern = IfxDma_ChannelPattern_0_disable,
            .dma_channelcfg.requestSource = IfxDma_ChannelRequestSource_peripheral,
            .dma_channelcfg.busPriority = DMA_PRIORITY_CARRIER4,
            .dma_channelcfg.hardwareRequestEnabled = TRUE,
            .dma_channelcfg.sourceAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.sourceAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.sourceAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.destinationAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.destinationAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.destinationAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.shadowControl = IfxDma_ChannelShadow_none,
            .dma_channelcfg.sourceCircularBufferEnabled = TRUE,
            .dma_channelcfg.destinationCircularBufferEnabled = TRUE,
            .dma_channelcfg.timestampEnabled = FALSE,
            .dma_channelcfg.wrapSourceInterruptEnabled = FALSE,
            .dma_channelcfg.wrapDestinationInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptEnabled = TRUE,
            .dma_channelcfg.channelInterruptControl = IfxDma_ChannelInterruptControl_thresholdLimitMatch,
            .dma_channelcfg.interruptRaiseThreshold = 0,
            .dma_channelcfg.transactionRequestLostInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptPriority = ISR_CONFIG_PRIORITY_CARRIER4_BUSINESS_INTERRUPT,
            .dma_channelcfg.channelInterruptTypeOfService = ISR_CONFIG_TOS_CARRIER4_BUSINESS_INTERRUPT,
        },
    },
    {
        .carrier_id = DEVICE_CARRIER_5,
        .dma_cfg =
        {
            .dma_module = &MODULE_DMA,
            .dma_modulecfg.dma = &MODULE_DMA,
            .dma_channelcfg.module = NULL_PTR,
            .dma_channelcfg.channelId = DMA_CHANNEL_CARRIER5,
            .dma_channelcfg.sourceAddress = 0,
            .dma_channelcfg.destinationAddress = 0,
            .dma_channelcfg.shadowAddress = 0,
            .dma_channelcfg.readDataCrc = 0,
            .dma_channelcfg.sourceDestinationAddressCrc = 0,
            .dma_channelcfg.transferCount = 0,
            .dma_channelcfg.blockMode = IfxDma_ChannelMove_1,
            .dma_channelcfg.requestMode = IfxDma_ChannelRequestMode_oneTransferPerRequest,
            .dma_channelcfg.operationMode = IfxDma_ChannelOperationMode_continuous,
            .dma_channelcfg.moveSize = IfxDma_ChannelMoveSize_8bit,
            .dma_channelcfg.pattern = IfxDma_ChannelPattern_0_disable,
            .dma_channelcfg.requestSource = IfxDma_ChannelRequestSource_peripheral,
            .dma_channelcfg.busPriority = DMA_PRIORITY_CARRIER5,
            .dma_channelcfg.hardwareRequestEnabled = TRUE,
            .dma_channelcfg.sourceAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.sourceAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.sourceAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.destinationAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.destinationAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.destinationAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.shadowControl = IfxDma_ChannelShadow_none,
            .dma_channelcfg.sourceCircularBufferEnabled = TRUE,
            .dma_channelcfg.destinationCircularBufferEnabled = TRUE,
            .dma_channelcfg.timestampEnabled = FALSE,
            .dma_channelcfg.wrapSourceInterruptEnabled = FALSE,
            .dma_channelcfg.wrapDestinationInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptEnabled = TRUE,
            .dma_channelcfg.channelInterruptControl = IfxDma_ChannelInterruptControl_thresholdLimitMatch,
            .dma_channelcfg.interruptRaiseThreshold = 0,
            .dma_channelcfg.transactionRequestLostInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptPriority = ISR_CONFIG_PRIORITY_CARRIER5_BUSINESS_INTERRUPT,
            .dma_channelcfg.channelInterruptTypeOfService = ISR_CONFIG_TOS_CARRIER5_BUSINESS_INTERRUPT,
        },
    },
    {
        .carrier_id = DEVICE_CARRIER_6,
        .dma_cfg =
        {
            .dma_module = &MODULE_DMA,
            .dma_modulecfg.dma = &MODULE_DMA,
            .dma_channelcfg.module = NULL_PTR,
            .dma_channelcfg.channelId = DMA_CHANNEL_CARRIER6,
            .dma_channelcfg.sourceAddress = 0,
            .dma_channelcfg.destinationAddress = 0,
            .dma_channelcfg.shadowAddress = 0,
            .dma_channelcfg.readDataCrc = 0,
            .dma_channelcfg.sourceDestinationAddressCrc = 0,
            .dma_channelcfg.transferCount = 0,
            .dma_channelcfg.blockMode = IfxDma_ChannelMove_1,
            .dma_channelcfg.requestMode = IfxDma_ChannelRequestMode_oneTransferPerRequest,
            .dma_channelcfg.operationMode = IfxDma_ChannelOperationMode_continuous,
            .dma_channelcfg.moveSize = IfxDma_ChannelMoveSize_8bit,
            .dma_channelcfg.pattern = IfxDma_ChannelPattern_0_disable,
            .dma_channelcfg.requestSource = IfxDma_ChannelRequestSource_peripheral,
            .dma_channelcfg.busPriority = DMA_PRIORITY_CARRIER6,
            .dma_channelcfg.hardwareRequestEnabled = TRUE,
            .dma_channelcfg.sourceAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.sourceAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.sourceAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.destinationAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.destinationAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.destinationAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.shadowControl = IfxDma_ChannelShadow_none,
            .dma_channelcfg.sourceCircularBufferEnabled = TRUE,
            .dma_channelcfg.destinationCircularBufferEnabled = TRUE,
            .dma_channelcfg.timestampEnabled = FALSE,
            .dma_channelcfg.wrapSourceInterruptEnabled = FALSE,
            .dma_channelcfg.wrapDestinationInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptEnabled = TRUE,
            .dma_channelcfg.channelInterruptControl = IfxDma_ChannelInterruptControl_thresholdLimitMatch,
            .dma_channelcfg.interruptRaiseThreshold = 0,
            .dma_channelcfg.transactionRequestLostInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptPriority = ISR_CONFIG_PRIORITY_CARRIER6_BUSINESS_INTERRUPT,
            .dma_channelcfg.channelInterruptTypeOfService = ISR_CONFIG_TOS_CARRIER6_BUSINESS_INTERRUPT,
        },
    },
    {
        .carrier_id = DEVICE_CARRIER_7,
        .dma_cfg =
        {
            .dma_module = &MODULE_DMA,
            .dma_modulecfg.dma = &MODULE_DMA,
            .dma_channelcfg.module = NULL_PTR,
            .dma_channelcfg.channelId = DMA_CHANNEL_CARRIER7,
            .dma_channelcfg.sourceAddress = 0,
            .dma_channelcfg.destinationAddress = 0,
            .dma_channelcfg.shadowAddress = 0,
            .dma_channelcfg.readDataCrc = 0,
            .dma_channelcfg.sourceDestinationAddressCrc = 0,
            .dma_channelcfg.transferCount = 0,
            .dma_channelcfg.blockMode = IfxDma_ChannelMove_1,
            .dma_channelcfg.requestMode = IfxDma_ChannelRequestMode_oneTransferPerRequest,
            .dma_channelcfg.operationMode = IfxDma_ChannelOperationMode_continuous,
            .dma_channelcfg.moveSize = IfxDma_ChannelMoveSize_8bit,
            .dma_channelcfg.pattern = IfxDma_ChannelPattern_0_disable,
            .dma_channelcfg.requestSource = IfxDma_ChannelRequestSource_peripheral,
            .dma_channelcfg.busPriority = DMA_PRIORITY_CARRIER7,
            .dma_channelcfg.hardwareRequestEnabled = TRUE,
            .dma_channelcfg.sourceAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.sourceAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.sourceAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.destinationAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.destinationAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.destinationAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.shadowControl = IfxDma_ChannelShadow_none,
            .dma_channelcfg.sourceCircularBufferEnabled = TRUE,
            .dma_channelcfg.destinationCircularBufferEnabled = TRUE,
            .dma_channelcfg.timestampEnabled = FALSE,
            .dma_channelcfg.wrapSourceInterruptEnabled = FALSE,
            .dma_channelcfg.wrapDestinationInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptEnabled = TRUE,
            .dma_channelcfg.channelInterruptControl = IfxDma_ChannelInterruptControl_thresholdLimitMatch,
            .dma_channelcfg.interruptRaiseThreshold = 0,
            .dma_channelcfg.transactionRequestLostInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptPriority = ISR_CONFIG_PRIORITY_CARRIER7_BUSINESS_INTERRUPT,
            .dma_channelcfg.channelInterruptTypeOfService = ISR_CONFIG_TOS_CARRIER7_BUSINESS_INTERRUPT,
        },
    },
    {
        .carrier_id = DEVICE_CARRIER_8,
        .dma_cfg =
        {
            .dma_module = &MODULE_DMA,
            .dma_modulecfg.dma = &MODULE_DMA,
            .dma_channelcfg.module = NULL_PTR,
            .dma_channelcfg.channelId = DMA_CHANNEL_CARRIER8,
            .dma_channelcfg.sourceAddress = 0,
            .dma_channelcfg.destinationAddress = 0,
            .dma_channelcfg.shadowAddress = 0,
            .dma_channelcfg.readDataCrc = 0,
            .dma_channelcfg.sourceDestinationAddressCrc = 0,
            .dma_channelcfg.transferCount = 0,
            .dma_channelcfg.blockMode = IfxDma_ChannelMove_1,
            .dma_channelcfg.requestMode = IfxDma_ChannelRequestMode_oneTransferPerRequest,
            .dma_channelcfg.operationMode = IfxDma_ChannelOperationMode_continuous,
            .dma_channelcfg.moveSize = IfxDma_ChannelMoveSize_8bit,
            .dma_channelcfg.pattern = IfxDma_ChannelPattern_0_disable,
            .dma_channelcfg.requestSource = IfxDma_ChannelRequestSource_peripheral,
            .dma_channelcfg.busPriority = DMA_PRIORITY_CARRIER8,
            .dma_channelcfg.hardwareRequestEnabled = TRUE,
            .dma_channelcfg.sourceAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.sourceAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.sourceAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.destinationAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.destinationAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.destinationAddressCircularRange = IfxDma_ChannelIncrementCircular_none,
            .dma_channelcfg.shadowControl = IfxDma_ChannelShadow_none,
            .dma_channelcfg.sourceCircularBufferEnabled = TRUE,
            .dma_channelcfg.destinationCircularBufferEnabled = TRUE,
            .dma_channelcfg.timestampEnabled = FALSE,
            .dma_channelcfg.wrapSourceInterruptEnabled = FALSE,
            .dma_channelcfg.wrapDestinationInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptEnabled = TRUE,
            .dma_channelcfg.channelInterruptControl = IfxDma_ChannelInterruptControl_thresholdLimitMatch,
            .dma_channelcfg.interruptRaiseThreshold = 0,
            .dma_channelcfg.transactionRequestLostInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptPriority = ISR_CONFIG_PRIORITY_CARRIER8_BUSINESS_INTERRUPT,
            .dma_channelcfg.channelInterruptTypeOfService = ISR_CONFIG_TOS_CARRIER8_BUSINESS_INTERRUPT,
        },
    },
};

device_carrier_runtime_t device_carrier_runtime_table[DEVICE_CARRIER_COUNT] =
{
    { .carrier_id = DEVICE_CARRIER_1, .device_carrier_callback = NULL_PTR },
    { .carrier_id = DEVICE_CARRIER_2, .device_carrier_callback = NULL_PTR },
    { .carrier_id = DEVICE_CARRIER_3, .device_carrier_callback = NULL_PTR },
    { .carrier_id = DEVICE_CARRIER_4, .device_carrier_callback = NULL_PTR },
    { .carrier_id = DEVICE_CARRIER_5, .device_carrier_callback = NULL_PTR },
    { .carrier_id = DEVICE_CARRIER_6, .device_carrier_callback = NULL_PTR },
    { .carrier_id = DEVICE_CARRIER_7, .device_carrier_callback = NULL_PTR },
    { .carrier_id = DEVICE_CARRIER_8, .device_carrier_callback = NULL_PTR },
};

device_carrier_cfg_t* device_carrier_cfg_table_get(void)
{
    return device_carrier_cfg_table;
}

device_carrier_runtime_t* device_carrier_runtime_table_get(void)
{
    return device_carrier_runtime_table;
}
