#include "./device_phototube_cfg.h"

#include "Ifx_Cfg.h"
#include "IfxVadc_cfg.h"

#define DEVICE_PHOTOTUBE_VADC_DIGITAL_FREQUENCY ((float32)(IFX_CFG_SCU_PLL_FREQUENCY / 2U))
#define DEVICE_PHOTOTUBE_VADC_MODULE_FREQUENCY  ((float32)(IFX_CFG_SCU_PLL_FREQUENCY / 2U))

#define DEVICE_PHOTOTUBE_VADC_SWITCH_COMPONENT_PERIOD 100000
#define DEVICE_PHOTOTUBE_VADC_SWITCH_COMPONENT_ON_DUTY (DEVICE_PHOTOTUBE_VADC_SWITCH_COMPONENT_PERIOD - 1u)
#define DEVICE_PHOTOTUBE_GROUP_INDEX_0 0u
#define DEVICE_PHOTOTUBE_GROUP_INDEX_1 1u
#define DEVICE_PHOTOTUBE_GROUP_INDEX_2 2u

#define DEVICE_PHOTOTUBE_GROUP0_SCAN_CHANNELS ((uint32)((1u << 0u) | (1u << 1u) | (1u << 2u) | (1u << 3u) | (1u << 8u) | (1u << 10u) | (1u << 11u) | (1u << 12u)))
#define DEVICE_PHOTOTUBE_GROUP1_SCAN_CHANNELS ((uint32)((1u << 0u) | (1u << 1u) | (1u << 4u) | (1u << 5u) | (1u << 8u) | (1u << 9u)))
#define DEVICE_PHOTOTUBE_GROUP2_SCAN_CHANNELS ((uint32)((1u << 3u) | (1u << 4u)))

device_phototube_switch_component_cfg_t device_phototube_switch_component_cfg =
{
    .tbu_channel = IfxGtm_Tbu_Ts_0,
    .switch_atom_pwm_cfg =
    {
        .gtm_module = &MODULE_GTM,
        .atom_pwm_modulecfg.gtm = &MODULE_GTM,
        .atom_pwm_modulecfg.atom = IfxGtm_Atom_0,
        .atom_pwm_modulecfg.atomChannel = IfxGtm_Atom_Ch_0,
        .atom_pwm_modulecfg.mode = IfxGtm_Atom_Mode_outputPwm,
        .atom_pwm_modulecfg.period = DEVICE_PHOTOTUBE_VADC_SWITCH_COMPONENT_PERIOD,
        .atom_pwm_modulecfg.dutyCycle = DEVICE_PHOTOTUBE_VADC_SWITCH_COMPONENT_ON_DUTY,
        .atom_pwm_modulecfg.signalLevel = Ifx_ActiveState_high,
        .atom_pwm_modulecfg.oneShotModeEnabled = FALSE,
        .atom_pwm_modulecfg.synchronousUpdateEnabled = TRUE,
        .atom_pwm_modulecfg.immediateStartEnabled = FALSE,
        .atom_pwm_modulecfg.interrupt.ccu0Enabled = FALSE,
        .atom_pwm_modulecfg.interrupt.ccu1Enabled = FALSE,
        .atom_pwm_modulecfg.interrupt.mode = IfxGtm_IrqMode_pulseNotify,
        .atom_pwm_modulecfg.interrupt.isrProvider = IfxSrc_Tos_cpu0,
        .atom_pwm_modulecfg.interrupt.isrPriority = 0u,
        .atom_pwm_modulecfg.pin.outputPin = &IfxGtm_ATOM0_0_TOUT9_P00_0_OUT,
        .atom_pwm_modulecfg.pin.outputMode = IfxPort_OutputMode_pushPull,
        .atom_pwm_modulecfg.pin.padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1,
    },
    .sample_atom_pwm_cfg =
    {
        .gtm_module = &MODULE_GTM,
        .atom_pwm_modulecfg.gtm = &MODULE_GTM,
        .atom_pwm_modulecfg.atom = IfxGtm_Atom_0,
        .atom_pwm_modulecfg.atomChannel = IfxGtm_Atom_Ch_6,
        .atom_pwm_modulecfg.mode = IfxGtm_Atom_Mode_outputPwm,
        .atom_pwm_modulecfg.period = DEVICE_PHOTOTUBE_VADC_SWITCH_COMPONENT_PERIOD,
        .atom_pwm_modulecfg.dutyCycle = DEVICE_PHOTOTUBE_VADC_SWITCH_COMPONENT_PERIOD / 2,
        .atom_pwm_modulecfg.signalLevel = Ifx_ActiveState_high,
        .atom_pwm_modulecfg.oneShotModeEnabled = FALSE,
        .atom_pwm_modulecfg.synchronousUpdateEnabled = TRUE,
        .atom_pwm_modulecfg.immediateStartEnabled = FALSE,
        .atom_pwm_modulecfg.interrupt.ccu0Enabled = TRUE,
        .atom_pwm_modulecfg.interrupt.ccu1Enabled = TRUE,
        .atom_pwm_modulecfg.interrupt.mode = IfxGtm_IrqMode_pulseNotify,
        .atom_pwm_modulecfg.interrupt.isrProvider = ISR_CONFIG_TOS_PHOTOTUBE_SWITCH_BUSINESS_INTERRUPT,
        .atom_pwm_modulecfg.interrupt.isrPriority = ISR_CONFIG_PRIORITY_PHOTOTUBE_SWITCH_BUSINESS_INTERRUPT,
        .atom_pwm_modulecfg.pin.outputPin = &IfxGtm_ATOM0_6_TOUT16_P00_7_OUT,
        .atom_pwm_modulecfg.pin.outputMode = IfxPort_OutputMode_pushPull,
        .atom_pwm_modulecfg.pin.padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1,
    },
};

device_phototube_switch_component_runtime_t device_phototube_switch_component_runtime;

IfxVadc_Adc_Config device_phototube_vadc_modulecfg =
{
    .vadc = &MODULE_VADC,
    .globalInputClass =
    {
        {
            .sampleTime = 1.0e-6f,
            .resolution = IfxVadc_ChannelResolution_12bit,
        },
        {
            .sampleTime = 1.0e-6f,
            .resolution = IfxVadc_ChannelResolution_12bit,
        },
    },
    .digitalFrequency = DEVICE_PHOTOTUBE_VADC_DIGITAL_FREQUENCY,
    .analogFrequency = IFXVADC_DEFAULT_ANALOG_FREQ,
    .moduleFrequency = DEVICE_PHOTOTUBE_VADC_MODULE_FREQUENCY,
    .startupCalibration = FALSE,
    .supplyVoltage = IfxVadc_LowSupplyVoltageSelect_5V,
};

IfxVadc_Adc_GroupConfig device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_VADC_GROUP_COUNT] =
{
    {
        .module = NULL_PTR,
        .groupId = IfxVadc_GroupId_0,
        .master = IfxVadc_GroupId_0,
        .inputClass =
        {
            {
                .sampleTime = 1.0e-6f,
                .resolution = IfxVadc_ChannelResolution_12bit,
            },
            {
                .sampleTime = 1.0e-6f,
                .resolution = IfxVadc_ChannelResolution_12bit,
            },
        },
        .scanRequest.autoscanEnabled = FALSE,
        .scanRequest.triggerConfig.gatingMode = IfxVadc_GatingMode_always,
        .scanRequest.triggerConfig.gatingSource = IfxVadc_GatingSource_0,
        .scanRequest.triggerConfig.triggerMode = IfxVadc_TriggerMode_noExternalTrigger,
        .scanRequest.triggerConfig.triggerSource = IfxVadc_TriggerSource_0,
        .scanRequest.requestSlotPrio = IfxVadc_RequestSlotPriority_highest,
        .scanRequest.requestSlotStartMode = IfxVadc_RequestSlotStartMode_waitForStart,
        .queueRequest.flushQueueAfterInit = FALSE,
        .queueRequest.triggerConfig.gatingMode = IfxVadc_GatingMode_always,
        .queueRequest.triggerConfig.gatingSource = IfxVadc_GatingSource_0,
        .queueRequest.triggerConfig.triggerMode = IfxVadc_TriggerMode_noExternalTrigger,
        .queueRequest.triggerConfig.triggerSource = IfxVadc_TriggerSource_0,
        .queueRequest.requestSlotPrio = IfxVadc_RequestSlotPriority_highest,
        .queueRequest.requestSlotStartMode = IfxVadc_RequestSlotStartMode_waitForStart,
        .backgroundScanRequest.autoBackgroundScanEnabled = FALSE,
        .backgroundScanRequest.triggerConfig.gatingMode = IfxVadc_GatingMode_always,
        .backgroundScanRequest.triggerConfig.gatingSource = IfxVadc_GatingSource_0,
        .backgroundScanRequest.triggerConfig.triggerMode = IfxVadc_TriggerMode_noExternalTrigger,
        .backgroundScanRequest.triggerConfig.triggerSource = IfxVadc_TriggerSource_0,
        .backgroundScanRequest.requestSlotPrio = IfxVadc_RequestSlotPriority_highest,
        .backgroundScanRequest.requestSlotStartMode = IfxVadc_RequestSlotStartMode_waitForStart,
        .disablePostCalibration = FALSE,
        .arbiter.arbiterRoundLength = IfxVadc_ArbitrationRounds_4_slots,
        .arbiter.requestSlotQueueEnabled = FALSE,
        .arbiter.requestSlotScanEnabled = TRUE,
        .arbiter.requestSlotBackgroundScanEnabled = FALSE,
    },
    {
        .module = NULL_PTR,
        .groupId = IfxVadc_GroupId_1,
        .master = IfxVadc_GroupId_1,
        .inputClass =
        {
            {
                .sampleTime = 1.0e-6f,
                .resolution = IfxVadc_ChannelResolution_12bit,
            },
            {
                .sampleTime = 1.0e-6f,
                .resolution = IfxVadc_ChannelResolution_12bit,
            },
        },
        .scanRequest.autoscanEnabled = FALSE,
        .scanRequest.triggerConfig.gatingMode = IfxVadc_GatingMode_always,
        .scanRequest.triggerConfig.gatingSource = IfxVadc_GatingSource_0,
        .scanRequest.triggerConfig.triggerMode = IfxVadc_TriggerMode_noExternalTrigger,
        .scanRequest.triggerConfig.triggerSource = IfxVadc_TriggerSource_0,
        .scanRequest.requestSlotPrio = IfxVadc_RequestSlotPriority_highest,
        .scanRequest.requestSlotStartMode = IfxVadc_RequestSlotStartMode_waitForStart,
        .queueRequest.flushQueueAfterInit = FALSE,
        .queueRequest.triggerConfig.gatingMode = IfxVadc_GatingMode_always,
        .queueRequest.triggerConfig.gatingSource = IfxVadc_GatingSource_0,
        .queueRequest.triggerConfig.triggerMode = IfxVadc_TriggerMode_noExternalTrigger,
        .queueRequest.triggerConfig.triggerSource = IfxVadc_TriggerSource_0,
        .queueRequest.requestSlotPrio = IfxVadc_RequestSlotPriority_highest,
        .queueRequest.requestSlotStartMode = IfxVadc_RequestSlotStartMode_waitForStart,
        .backgroundScanRequest.autoBackgroundScanEnabled = FALSE,
        .backgroundScanRequest.triggerConfig.gatingMode = IfxVadc_GatingMode_always,
        .backgroundScanRequest.triggerConfig.gatingSource = IfxVadc_GatingSource_0,
        .backgroundScanRequest.triggerConfig.triggerMode = IfxVadc_TriggerMode_noExternalTrigger,
        .backgroundScanRequest.triggerConfig.triggerSource = IfxVadc_TriggerSource_0,
        .backgroundScanRequest.requestSlotPrio = IfxVadc_RequestSlotPriority_highest,
        .backgroundScanRequest.requestSlotStartMode = IfxVadc_RequestSlotStartMode_waitForStart,
        .disablePostCalibration = FALSE,
        .arbiter.arbiterRoundLength = IfxVadc_ArbitrationRounds_4_slots,
        .arbiter.requestSlotQueueEnabled = FALSE,
        .arbiter.requestSlotScanEnabled = TRUE,
        .arbiter.requestSlotBackgroundScanEnabled = FALSE,
    },
    {
        .module = NULL_PTR,
        .groupId = IfxVadc_GroupId_2,
        .master = IfxVadc_GroupId_2,
        .inputClass =
        {
            {
                .sampleTime = 1.0e-6f,
                .resolution = IfxVadc_ChannelResolution_12bit,
            },
            {
                .sampleTime = 1.0e-6f,
                .resolution = IfxVadc_ChannelResolution_12bit,
            },
        },
        .scanRequest.autoscanEnabled = FALSE,
        .scanRequest.triggerConfig.gatingMode = IfxVadc_GatingMode_always,
        .scanRequest.triggerConfig.gatingSource = IfxVadc_GatingSource_0,
        .scanRequest.triggerConfig.triggerMode = IfxVadc_TriggerMode_noExternalTrigger,
        .scanRequest.triggerConfig.triggerSource = IfxVadc_TriggerSource_0,
        .scanRequest.requestSlotPrio = IfxVadc_RequestSlotPriority_highest,
        .scanRequest.requestSlotStartMode = IfxVadc_RequestSlotStartMode_waitForStart,
        .queueRequest.flushQueueAfterInit = FALSE,
        .queueRequest.triggerConfig.gatingMode = IfxVadc_GatingMode_always,
        .queueRequest.triggerConfig.gatingSource = IfxVadc_GatingSource_0,
        .queueRequest.triggerConfig.triggerMode = IfxVadc_TriggerMode_noExternalTrigger,
        .queueRequest.triggerConfig.triggerSource = IfxVadc_TriggerSource_0,
        .queueRequest.requestSlotPrio = IfxVadc_RequestSlotPriority_highest,
        .queueRequest.requestSlotStartMode = IfxVadc_RequestSlotStartMode_waitForStart,
        .backgroundScanRequest.autoBackgroundScanEnabled = FALSE,
        .backgroundScanRequest.triggerConfig.gatingMode = IfxVadc_GatingMode_always,
        .backgroundScanRequest.triggerConfig.gatingSource = IfxVadc_GatingSource_0,
        .backgroundScanRequest.triggerConfig.triggerMode = IfxVadc_TriggerMode_noExternalTrigger,
        .backgroundScanRequest.triggerConfig.triggerSource = IfxVadc_TriggerSource_0,
        .backgroundScanRequest.requestSlotPrio = IfxVadc_RequestSlotPriority_highest,
        .backgroundScanRequest.requestSlotStartMode = IfxVadc_RequestSlotStartMode_waitForStart,
        .disablePostCalibration = FALSE,
        .arbiter.arbiterRoundLength = IfxVadc_ArbitrationRounds_4_slots,
        .arbiter.requestSlotQueueEnabled = FALSE,
        .arbiter.requestSlotScanEnabled = TRUE,
        .arbiter.requestSlotBackgroundScanEnabled = FALSE,
    },
};

IfxVadc_Adc_ChannelConfig device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_COUNT] =
{
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_0,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_0,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_1,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_1,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_2,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_2,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_3,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_3,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = ISR_CONFIG_PRIORITY_PHOTOTUBE_GROUP0_BUSINESS_INTERRUPT,
        .channelPriority = 0u,
        .resultServProvider = ISR_CONFIG_TOS_PHOTOTUBE_GROUP0_BUSINESS_INTERRUPT,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_12,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_4,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_11,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_5,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_10,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_6,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_8,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_7,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_0,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_0,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_1,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_1,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_4,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_2,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_5,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_3,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_8,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_4,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = ISR_CONFIG_PRIORITY_PHOTOTUBE_GROUP1_BUSINESS_INTERRUPT,
        .channelPriority = 0u,
        .resultServProvider = ISR_CONFIG_TOS_PHOTOTUBE_GROUP1_BUSINESS_INTERRUPT,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_9,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_5,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = 0u,
        .channelPriority = 0u,
        .resultServProvider = IfxSrc_Tos_dma,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_3,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_0,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
    {
        .globalResultUsage = FALSE,
        .synchonize = FALSE,
        .backgroundChannel = FALSE,
        .rightAlignedStorage = TRUE,
        .resultPriority = ISR_CONFIG_PRIORITY_PHOTOTUBE_GROUP2_BUSINESS_INTERRUPT,
        .channelPriority = 0u,
        .resultServProvider = ISR_CONFIG_TOS_PHOTOTUBE_GROUP2_BUSINESS_INTERRUPT,
        .channelServProvider = IfxSrc_Tos_cpu0,
        .resultSrcNr = IfxVadc_SrcNr_group0,
        .channelSrcNr = IfxVadc_SrcNr_group0,
        .channelId = IfxVadc_ChannelId_4,
        .inputClass = IfxVadc_InputClasses_group0,
        .reference = IfxVadc_ChannelReference_standard,
        .resultRegister = IfxVadc_ChannelResult_1,
        .lowerBoundary = IfxVadc_BoundarySelection_group0,
        .upperBoundary = IfxVadc_BoundarySelection_group0,
        .boundaryMode = IfxVadc_BoundaryExtension_standard,
        .limitCheck = IfxVadc_LimitCheck_noCheck,
        .group = NULL_PTR,
    },
};

IfxVadc_Adc device_phototube_vadc_modulehn;
IfxVadc_Adc_Group device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_VADC_GROUP_COUNT];
IfxVadc_Adc_Channel device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_COUNT];

device_phototube_group_cfg_t device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_VADC_GROUP_COUNT] =
{
    {
        .vadc_scan_channels = DEVICE_PHOTOTUBE_GROUP0_SCAN_CHANNELS,
        .dma_cfg =
        {
            .dma_module = &MODULE_DMA,
            .dma_modulecfg.dma = &MODULE_DMA,
            .dma_channelcfg.module = NULL_PTR,
            .dma_channelcfg.channelId = DMA_CHANNEL_PHOTOTUBE_GROUP0_EVADC_TO_INTERRUPT,
            .dma_channelcfg.sourceAddress = 0u,
            .dma_channelcfg.destinationAddress = 0u,
            .dma_channelcfg.shadowAddress = 0u,
            .dma_channelcfg.readDataCrc = 0u,
            .dma_channelcfg.sourceDestinationAddressCrc = 0u,
            .dma_channelcfg.transferCount = 8,
            .dma_channelcfg.blockMode = IfxDma_ChannelMove_1,
            .dma_channelcfg.requestMode = IfxDma_ChannelRequestMode_completeTransactionPerRequest,
            .dma_channelcfg.operationMode = IfxDma_ChannelOperationMode_continuous,
            .dma_channelcfg.moveSize = IfxDma_ChannelMoveSize_16bit,
            .dma_channelcfg.pattern = IfxDma_ChannelPattern_0_disable,
            .dma_channelcfg.requestSource = IfxDma_ChannelRequestSource_peripheral,
            .dma_channelcfg.busPriority = DMA_PRIORITY_PHOTOTUBE_GROUP0_EVADC_TO_INTERRUPT,
            .dma_channelcfg.hardwareRequestEnabled = TRUE,
            .dma_channelcfg.sourceAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.sourceAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.sourceAddressCircularRange = IfxDma_ChannelIncrementCircular_16,
            .dma_channelcfg.destinationAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.destinationAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.destinationAddressCircularRange = IfxDma_ChannelIncrementCircular_16,
            .dma_channelcfg.shadowControl = IfxDma_ChannelShadow_none,
            .dma_channelcfg.sourceCircularBufferEnabled = TRUE,
            .dma_channelcfg.destinationCircularBufferEnabled = TRUE,
            .dma_channelcfg.timestampEnabled = FALSE,
            .dma_channelcfg.wrapSourceInterruptEnabled = FALSE,
            .dma_channelcfg.wrapDestinationInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptEnabled = TRUE,
            .dma_channelcfg.channelInterruptControl = IfxDma_ChannelInterruptControl_thresholdLimitMatch,
            .dma_channelcfg.interruptRaiseThreshold = 0u,
            .dma_channelcfg.transactionRequestLostInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptPriority = ISR_CONFIG_PRIORITY_PHOTOTUBE_GROUP0_BUSINESS_INTERRUPT,
            .dma_channelcfg.channelInterruptTypeOfService = ISR_CONFIG_TOS_PHOTOTUBE_GROUP0_BUSINESS_INTERRUPT,
        },
    },
    {
        .vadc_scan_channels = DEVICE_PHOTOTUBE_GROUP1_SCAN_CHANNELS,
        .dma_cfg =
        {
            .dma_module = &MODULE_DMA,
            .dma_modulecfg.dma = &MODULE_DMA,
            .dma_channelcfg.module = NULL_PTR,
            .dma_channelcfg.channelId = DMA_CHANNEL_PHOTOTUBE_GROUP1_EVADC_TO_INTERRUPT,
            .dma_channelcfg.sourceAddress = 0u,
            .dma_channelcfg.destinationAddress = 0u,
            .dma_channelcfg.shadowAddress = 0u,
            .dma_channelcfg.readDataCrc = 0u,
            .dma_channelcfg.sourceDestinationAddressCrc = 0u,
            .dma_channelcfg.transferCount = 8,
            .dma_channelcfg.blockMode = IfxDma_ChannelMove_1,
            .dma_channelcfg.requestMode = IfxDma_ChannelRequestMode_completeTransactionPerRequest,
            .dma_channelcfg.operationMode = IfxDma_ChannelOperationMode_continuous,
            .dma_channelcfg.moveSize = IfxDma_ChannelMoveSize_16bit,
            .dma_channelcfg.pattern = IfxDma_ChannelPattern_0_disable,
            .dma_channelcfg.requestSource = IfxDma_ChannelRequestSource_peripheral,
            .dma_channelcfg.busPriority = DMA_PRIORITY_PHOTOTUBE_GROUP1_EVADC_TO_INTERRUPT,
            .dma_channelcfg.hardwareRequestEnabled = TRUE,
            .dma_channelcfg.sourceAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.sourceAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.sourceAddressCircularRange = IfxDma_ChannelIncrementCircular_16,
            .dma_channelcfg.destinationAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.destinationAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.destinationAddressCircularRange = IfxDma_ChannelIncrementCircular_16,
            .dma_channelcfg.shadowControl = IfxDma_ChannelShadow_none,
            .dma_channelcfg.sourceCircularBufferEnabled = TRUE,
            .dma_channelcfg.destinationCircularBufferEnabled = TRUE,
            .dma_channelcfg.timestampEnabled = FALSE,
            .dma_channelcfg.wrapSourceInterruptEnabled = FALSE,
            .dma_channelcfg.wrapDestinationInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptEnabled = TRUE,
            .dma_channelcfg.channelInterruptControl = IfxDma_ChannelInterruptControl_thresholdLimitMatch,
            .dma_channelcfg.interruptRaiseThreshold = 0u,
            .dma_channelcfg.transactionRequestLostInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptPriority = ISR_CONFIG_PRIORITY_PHOTOTUBE_GROUP1_BUSINESS_INTERRUPT,
            .dma_channelcfg.channelInterruptTypeOfService = ISR_CONFIG_TOS_PHOTOTUBE_GROUP1_BUSINESS_INTERRUPT,
        },
    },
    {
        .vadc_scan_channels = DEVICE_PHOTOTUBE_GROUP2_SCAN_CHANNELS,
        .dma_cfg =
        {
            .dma_module = &MODULE_DMA,
            .dma_modulecfg.dma = &MODULE_DMA,
            .dma_channelcfg.module = NULL_PTR,
            .dma_channelcfg.channelId = DMA_CHANNEL_PHOTOTUBE_GROUP2_EVADC_TO_INTERRUPT,
            .dma_channelcfg.sourceAddress = 0u,
            .dma_channelcfg.destinationAddress = 0u,
            .dma_channelcfg.shadowAddress = 0u,
            .dma_channelcfg.readDataCrc = 0u,
            .dma_channelcfg.sourceDestinationAddressCrc = 0u,
            .dma_channelcfg.transferCount = 2,
            .dma_channelcfg.blockMode = IfxDma_ChannelMove_1,
            .dma_channelcfg.requestMode = IfxDma_ChannelRequestMode_completeTransactionPerRequest,
            .dma_channelcfg.operationMode = IfxDma_ChannelOperationMode_continuous,
            .dma_channelcfg.moveSize = IfxDma_ChannelMoveSize_16bit,
            .dma_channelcfg.pattern = IfxDma_ChannelPattern_0_disable,
            .dma_channelcfg.requestSource = IfxDma_ChannelRequestSource_peripheral,
            .dma_channelcfg.busPriority = DMA_PRIORITY_PHOTOTUBE_GROUP2_EVADC_TO_INTERRUPT,
            .dma_channelcfg.hardwareRequestEnabled = TRUE,
            .dma_channelcfg.sourceAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.sourceAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.sourceAddressCircularRange = IfxDma_ChannelIncrementCircular_4,
            .dma_channelcfg.destinationAddressIncrementStep = IfxDma_ChannelIncrementStep_1,
            .dma_channelcfg.destinationAddressIncrementDirection = IfxDma_ChannelIncrementDirection_positive,
            .dma_channelcfg.destinationAddressCircularRange = IfxDma_ChannelIncrementCircular_4,
            .dma_channelcfg.shadowControl = IfxDma_ChannelShadow_none,
            .dma_channelcfg.sourceCircularBufferEnabled = TRUE,
            .dma_channelcfg.destinationCircularBufferEnabled = TRUE,
            .dma_channelcfg.timestampEnabled = FALSE,
            .dma_channelcfg.wrapSourceInterruptEnabled = FALSE,
            .dma_channelcfg.wrapDestinationInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptEnabled = TRUE,
            .dma_channelcfg.channelInterruptControl = IfxDma_ChannelInterruptControl_thresholdLimitMatch,
            .dma_channelcfg.interruptRaiseThreshold = 0u,
            .dma_channelcfg.transactionRequestLostInterruptEnabled = FALSE,
            .dma_channelcfg.channelInterruptPriority = ISR_CONFIG_PRIORITY_PHOTOTUBE_GROUP2_BUSINESS_INTERRUPT,
            .dma_channelcfg.channelInterruptTypeOfService = ISR_CONFIG_TOS_PHOTOTUBE_GROUP2_BUSINESS_INTERRUPT,
        },
    },
};

uint16 device_phototube_dma_receive_buffer[DEVICE_PHOTOTUBE_COUNT] = {0u};

device_phototube_group_runtime_t device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_VADC_GROUP_COUNT] =
{
    {
        .device_phototube_group_callback = NULL_PTR,
    },
    {
        .device_phototube_group_callback = NULL_PTR,
    },
    {
        .device_phototube_group_callback = NULL_PTR,
    },
};

device_phototube_cfg_t device_phototube_cfg_table[DEVICE_PHOTOTUBE_COUNT] =
{
    {
        .phototube_id = DEVICE_PHOTOTUBE_1,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_1],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_2,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_2],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_3,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_3],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_4,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_4],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_5,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_5],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_6,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_6],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_7,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_7],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_8,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_8],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_9,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_9],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_10,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_10],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_11,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_11],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_12,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_12],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_13,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_13],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_14,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_14],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_15,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_2],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_15],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_2],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_16,
        .phototube_switch_component_cfg = &device_phototube_switch_component_cfg,
        .vadc_cfg =
        {
            .vadc_module = &MODULE_VADC,
            .vadc_modulecfg = &device_phototube_vadc_modulecfg,
            .vadc_groupcfg = &device_phototube_vadc_groupcfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_2],
            .vadc_channelcfg = &device_phototube_vadc_channelcfg_table[DEVICE_PHOTOTUBE_16],
        },
        .phototube_group_cfg = &device_phototube_group_cfg_table[DEVICE_PHOTOTUBE_GROUP_INDEX_2],
    },
};

device_phototube_runtime_t device_phototube_runtime_table[DEVICE_PHOTOTUBE_COUNT] =
{
    {
        .phototube_id = DEVICE_PHOTOTUBE_1,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_1],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[0],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_2,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_2],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[1],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_3,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_3],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[2],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_4,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_4],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[3],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_5,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_5],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[4],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_6,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_6],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[5],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_7,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_7],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[6],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_8,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_8],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_0],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[7],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_9,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_9],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[8],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_10,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_10],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[9],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_11,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_11],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[10],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_12,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_12],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[11],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_13,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_13],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[12],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_14,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_14],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_1],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[13],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_15,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_2],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_15],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_2],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[14],
    },
    {
        .phototube_id = DEVICE_PHOTOTUBE_16,
        .phototube_switch_component_runtime = &device_phototube_switch_component_runtime,
        .vadc_runtime =
        {
            .vadc_modulehn = &device_phototube_vadc_modulehn,
            .vadc_grouphn = &device_phototube_vadc_grouphn_table[DEVICE_PHOTOTUBE_GROUP_INDEX_2],
            .vadc_channelhn = &device_phototube_vadc_channelhn_table[DEVICE_PHOTOTUBE_16],
        },
        .phototube_group_runtime = &device_phototube_group_runtime_table[DEVICE_PHOTOTUBE_GROUP_INDEX_2],
        .dma_receive_buffer = &device_phototube_dma_receive_buffer[15],
    },
};

device_phototube_cfg_t *device_phototube_cfg_table_get(void)
{
    return device_phototube_cfg_table;
}

device_phototube_runtime_t *device_phototube_runtime_table_get(void)
{
    return device_phototube_runtime_table;
}
